repos:
    - repo: local
      hooks:
          - id: unittests
            name: run unit tests
            entry: python -m unittest
            language: system
            pass_filenames: false
            args: ["discover"]
