name: test self-hosted

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test-self-hosted.yml"
      - "sonar-project.properties"

jobs:
  unittest:
    runs-on:
      # - ubuntu-latest
      - self-hosted
      - gpu

    env:
      NUMBA_CUDA_USE_NVIDIA_BINDING: 1

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install cuda-python==11.4
          pip install -r requirements.txt

      - name: Numba informations
        run: |
          numba -s

      - name: Running pytest
        run: |
          python -m pytest -v --cov --cov-report=xml --cov-report=html
          python -m coverage xml -i

      - name: Override Coverage Source Path for Sonar
        run: |
          sed -i "s/<source>\/home\/runner\/_work\/pyles\/pyles<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/_work/pyles/pyles/coverage.xml

      - run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 1

  coverage:
    needs: unittest
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
