name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/mkdocs.yml"
      - "!src/**"
      - "!tests/**"
  workflow_run:
    workflows:
      - Unit tests on self-hosted with Conda
    types:
      - completed

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          lfs: false

      - name: Download artifact
        uses: actions/download-artifact@v3
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          name: coverage-report

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          # EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt