name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/mkdocs.yml"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          lfs: false

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          # EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt