name: create profiler report

on:
  push:
    branches:
      - master
    paths:
      - "pyles/**"
      - "main.py"
      - ".github/workflows/profiler.yml"

jobs:
  docs:
    runs-on: 
      - self-hosted
      - gpu

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py-spy plotly kaleido
          pip install -r requirements.txt

      - name: Generate Profile
        run: |
          py-spy record --nonblocking --format speedscope --output profile.speedscope.json -- python3 main.py

      - name: Send image as commit
        run: |
          cml publish ./main.png --md >> report.md
          cml send-comment report.md
