on:
  push:
    branches:
      - master
    paths:
      - "pyles/**"
      - "main.py"

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py-spy
          pip install -r requirements.txt

      - name: Generate Profile
        run: |
          py-spy record --format speedscope --output profile.speedscope.json -- python3 main.py

      - name: Commit documentation changes
        run: |
          git clone https://github.com/agbv/pyles.git --branch gh-pages --single-branch gh-pages
          cp profile.speedscope.json gh-pages/
          cd pyles-git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Genereate profiler data" -a || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
