name: create profiler report

on:
  push:
    branches:
      - master
    paths:
      - "pyles/**"
      - "main.py"
      - ".github/workflows/profiler.yml"

jobs:
  profiler:
    runs-on: 
      - self-hosted
      - gpu

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: pyles-conda
          environment-file: conda-env.yml
          use-only-tar-bz2: true
          auto-activate-base: false

      - name: Install profiler dependencies
        run: |
          conda install py-spy plotly kaleido
          
      - run: echo $CONDA

      - name: Generate Profile
        run: |
          py-spy record --nonblocking --format speedscope --output profile.speedscope.json -- python3 main.py

      - name: Send image as commit
        run: |
          cml publish ./main.png --md >> report.md
          cml send-comment report.md
