name: Unit tests on self-hosted with Conda

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test-self-hosted-conda.yml"
      - "sonar-project.properties"

jobs:
  unittest:
    runs-on:
      - self-hosted
      - gpu

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda-env.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: pyles-conda
          environment-file: conda-env.yml
          use-only-tar-bz2: true
          auto-activate-base: false
          #python-version: 3.10
          #condarc-file: etc/example-condarc.yml
      - run: |
          conda info
          conda list
      
      # - run: |
      #     # conda env create --force -f conda-env.yml
      #     conda init bash
      #     conda activate pyles-conda
      #     conda info
      #     conda list

      - run: |
          numba -s

  #     - name: Set up Python 3.10
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pytest pytest-cov coverage
  #         pip install -r requirements.txt

  #     - name: Numba informations
  #       run: |
  #         numba -s

  #     - name: Running pytest
  #       run: |
  #         python -m pytest -v --cov --cov-report=xml --cov-report=html
  #         python -m coverage xml -i

  #     - name: Override Coverage Source Path for Sonar
  #       run: |
  #         sed -i "s/<source>\/home\/runner\/_work\/pyles\/pyles<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/_work/pyles/pyles/coverage.xml

  #     - run: ls -la

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage-report
  #         path: coverage.xml
  #         retention-days: 1

  # coverage:
  #   needs: unittest
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Set up Git repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #         lfs: false

  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: coverage-report
      
  #     - name: SonarQube Scan
  #       uses: sonarsource/sonarqube-scan-action@master
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
