name: test

on:
  push:
    branches:
      - master
    paths:
      - "pyles/**"
      - "tests/**"
      - ".github/workflows/test.yml"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install -r requirements.txt

      - name: Running pytest
        run: |
          python -m pytest -v --cov --cov-report=xml --cov-report=html
          python -m coverage xml -i

      - name: Override Coverage Source Path for Sonar
        run: |
          sed -i "s/<source>\/home\/runner\/work\/pyles\/pyles<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/pyles/pyles/coverage.xml

      # - name: Analysing the code with pylint
      #   continue-on-error: true
      #   run: |
      #     pylint src/git_graph_automation

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
