name: test

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
      - "sonar-project.properties"

jobs:
  unittest:
    runs-on:
      # - ubuntu-latest
      - self-hosted
      - gpu

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false

      - name: cml_run
        run: |
          echo 'Hi from CML!' >> report.md
          cml send-comment report.md

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install -r requirements.txt

      - name: Running pytest
        run: |
          python -m pytest -v --cov --cov-report=xml --cov-report=html
          python -m coverage xml -i

      - name: Override Coverage Source Path for Sonar
        run: |
          sed -i "s/<source>\/home\/runner\/_work\/pyles\/pyles<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/_work/pyles/pyles/coverage.xml

      - name: Store in cache
        uses: actions/cache@v3
        with:
          path: /home/runner/_work/pyles/pyles/*.xml
          key: pyles-coverage-report

  coverage:
    needs: unittest
    runs-on: ubuntu-latest

    steps:
      - name: Restore from cache
        uses: actions/checkout@v3
        with:
          path: /home/runner/work/pyles/pyles/*.xml
          key: pyles-coverage-report

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
