name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 100

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Running pytest
        run: |
          python -m pytest -v --cov --cov-report=xml --cov-report=html

      # - name: Analysing the code with pylint
      #   continue-on-error: true
      #   run: |
      #     pylint src/git_graph_automation

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}